import { fr, op } from "./helpers.mjs";

const W = 1;

export default [
  {
    id: "recession", n: 1, week: W, tags: ["L1"],
    term: "Recession",
    simple: "A broad, temporary fall in economic activity: output, jobs, trade and production all shrink together.",
    more: [
      "The headline rule of thumb is <b>two quarters in a row of falling real GDP</b>, but the official US referee, the NBER's Business Cycle Dating Committee, looks at many monthly indicators (employment, real income, industrial production, sales) and asks whether the fall is <i>significant, widespread and lasting</i>.",
      "Opposite: an expansion. The turning points are called the peak (expansion ends) and the trough (recession ends).",
    ],
    connections: ["gdp", "real-gdp", "unemployment-rate", "natural-rate"],
    example: "In the first half of 2022 real GDP fell for two straight quarters in the first estimates, yet the NBER never called a recession: employment was growing fast the whole time. The two-quarter rule is a shortcut, not the definition.",
    numbers: [
      ["Great Recession (NBER)", "Dec 2007 – Jun 2009"],
      ["Its length", "18 months"],
      ["COVID recession", "Feb – Apr 2020"],
      ["Its length (shortest ever)", "2 months"],
      ["Peak unemployment, 2009", "10.0%"],
      ["Peak unemployment, Apr 2020", "14.8%"],
    ],
    numbersSource: "NBER business-cycle dates; BLS unemployment rate.",
    graph: "businessCycle",
  },
  {
    id: "gdp", n: 2, week: W, tags: ["L2", "Ch 2"],
    term: "Gross domestic product (GDP)",
    simple: "The market value of all <b>final</b> goods and services produced inside a country in a period.",
    more: [
      "Three ways to measure it, all giving the same number (the circular flow): <b>total spending</b> on final output, <b>total income</b> earned producing it, and <b>total value added</b> by every firm.",
      "Word by word: <i>market value</i> (uses prices to add apples and haircuts), <i>final</i> (no intermediate goods, or you double count), <i>produced</i> (used cars and stocks don't count), <i>domestic</i> (inside the borders, whoever owns the factory), <i>in a period</i> (a flow, per quarter or year).",
    ],
    connections: ["expenditure-identity", "value-added", "nominal-gdp", "stock-flow"],
    example: "A Honda built in Ohio counts in US GDP even though Honda is Japanese. A used Honda resold this year adds nothing (only the dealer's service fee counts, as a service produced now).",
    numbers: [
      ["US nominal GDP, 2025", "≈ $30.8 trillion"],
      ["US nominal GDP, 2024", "≈ $29.3 trillion"],
      ["Real GDP growth, Q2 2026", "2.2% (annual rate)"],
      ["China, 2025", "¥140.2 trillion"],
    ],
    numbersSource: "BEA (2025 total via Statista/Wikipedia summaries of BEA; Q2 2026 third estimate, released Sep 30, 2026); China NBS.",
    graph: "circularFlow",
  },
  {
    id: "expenditure-identity", n: 3, week: W, tags: ["L2", "Ch 2"],
    term: "Expenditure identity",
    simple: "Output equals what's spent on it: consumption plus investment plus government purchases plus net exports.",
    formula: `<i>Y</i>${op("=")}<i>C</i>${op("+")}<i>I</i>${op("+")}<i>G</i>${op("+")}<i>NX</i>`,
    more: [
      "It is an <b>identity</b>: true by definition, because of how the accounts are built. Anything produced but not sold goes into inventories, which count as investment, so the two sides always balance.",
      "Rearranged it gives the saving identity used all through Week 2: <i>Y − C − G = I + NX</i>, i.e. national saving equals investment plus net exports (and just <i>S = I</i> in a closed economy).",
    ],
    connections: ["consumption", "investment", "government", "net-exports", "national-saving"],
    example: "If Ford builds a truck in December and it's still on the lot on December 31, it counts as inventory investment this year. When it sells next year, consumption rises and inventory investment falls by the same amount: no double counting.",
    numbers: [
      ["C", "≈ 68% of GDP"],
      ["I", "≈ 18%"],
      ["G", "≈ 17%"],
      ["NX", "≈ −3%"],
    ],
    numbersSource: "Approximate 2025 shares, BEA national accounts. Consumption share 67.9% in Q3 2025 (FRED).",
    graph: { key: "gdpShares" },
  },
  {
    id: "consumption", n: 4, week: W, tags: ["L2"],
    term: "Consumption (C)",
    simple: "Spending by households on goods and services. The biggest part of GDP, about two-thirds.",
    more: [
      "Includes durables (cars, appliances), nondurables (food, clothing) and services (rent, haircuts, health care). Services are the largest piece.",
      "<b>Exception:</b> buying a newly built house counts as <i>residential investment</i>, not consumption. Rent (including the rent homeowners implicitly “pay themselves”) is consumption.",
    ],
    connections: ["expenditure-identity", "consumption-function", "mpc", "disposable-income"],
    example: "Your Netflix subscription, a Chipotle burrito and a new iPhone all count. Your tuition counts too, as a service.",
    numbers: [
      ["Share of US GDP, Q3 2025", "67.9%"],
      ["Personal saving rate, Jul 2026", "3.0%"],
    ],
    numbersSource: "BEA via FRED; BEA Personal Income and Outlays, July 2026.",
    graph: { key: "gdpShares", args: { hi: "C" } },
  },
  {
    id: "investment", n: 5, week: W, starred: true, tags: ["PE Q19", "Ch 2 #4"],
    term: "Investment (I)",
    simple: "Spending on goods bought for <b>future use</b>: business equipment, buildings, new houses and inventories.",
    more: [
      "Three pieces: <b>business fixed investment</b> (machines, software, factories), <b>residential investment</b> (new housing) and <b>inventory investment</b> (the change in unsold stock).",
      "<b>Exam trap:</b> buying stocks or bonds is <i>not</i> investment in GDP. That is a financial transaction that swaps one asset for another; nothing new is produced.",
      "It's the most volatile part of GDP: firms postpone projects when the outlook darkens, so investment falls far more than consumption in a recession.",
    ],
    connections: ["expenditure-identity", "investment-function", "loanable-funds", "capital-accumulation"],
    example: "A brewery buying a new fermentation tank, a family buying a newly built home, and a store stocking up on unsold inventory are all investment. Buying Apple shares is not.",
    numbers: [
      ["Share of US GDP", "≈ 18%"],
    ],
    numbersSource: "Approximate 2025 share, BEA.",
    played: [
      "Ask: was something newly produced for future use? If yes, investment.",
      "A used factory changing hands: no new output, so it's not investment (it just transfers ownership).",
      "Inventories rose by $50B this year: +$50B to I, even though nothing was sold.",
    ],
    graph: { key: "gdpShares", args: { hi: "I" } },
  },
  {
    id: "government", n: 6, week: W, tags: ["Ch 2 #4", "BG"],
    term: "Government purchases (G)",
    simple: "Goods and services the government buys, like computers for a public school or a soldier's salary.",
    more: [
      "<b>Transfer payments are not included</b>: Social Security, unemployment benefits and welfare move money from one person to another without buying anything produced. They show up in GDP only when the recipient spends them (as C).",
      "Covers federal, state and local government, both consumption (salaries, supplies) and investment (roads, buildings).",
    ],
    connections: ["expenditure-identity", "public-saving", "crowding-out", "balanced-budget"],
    example: "When a city pays a contractor to repave a road, that's G. When the government sends a Social Security check, that's a transfer: G doesn't change.",
    numbers: [
      ["Share of US GDP", "≈ 17%"],
      ["Federal deficit, FY2025", "$1.8 trillion"],
      ["Federal outlays, FY2025", "$7.0 trillion"],
    ],
    numbersSource: "BEA (share, approximate); CBO Monthly Budget Review, FY2025. Federal outlays include transfers and interest, which are not G.",
    played: [
      "Federal outlays ($7.0T) are far bigger than federal G because most of it is transfers (Social Security, Medicare) and interest on the debt.",
      "Only the part that buys goods and services, like defense purchases or federal salaries, enters G.",
    ],
    graph: { key: "gdpShares", args: { hi: "G" } },
  },
  {
    id: "net-exports", n: 7, week: W, tags: ["Ch 2 #4"],
    term: "Net exports (NX)",
    simple: "Exports minus imports. Positive is a trade surplus, negative a trade deficit.",
    formula: `<i>NX</i>${op("=")}<i>EX</i>${op("−")}<i>IM</i>`,
    more: [
      "Imports are subtracted because they are already counted inside C, I and G. Subtracting them strips out spending on goods made abroad, so GDP only counts domestic production.",
      "A US good sold to a buyer abroad counts in NX (as an export).",
    ],
    connections: ["expenditure-identity", "gdp", "cpi-vs-deflator"],
    example: "You buy a $1,000 Samsung TV made in Korea: C rises $1,000 and IM rises $1,000, so US GDP is unchanged. Boeing sells a plane to Air France: EX rises and US GDP rises.",
    numbers: [
      ["US share of GDP", "≈ −3%"],
      ["US goods & services deficit, 2024", "≈ $918 billion"],
    ],
    numbersSource: "BEA/Census annual trade release for 2024; share approximate.",
    graph: { key: "gdpShares", args: { hi: "NX" } },
  },
  {
    id: "stock-flow", n: 8, week: W, tags: ["L2"],
    term: "Stock vs flow",
    simple: "A <b>flow</b> is measured per period of time; a <b>stock</b> is measured at a point in time.",
    more: [
      "Flows: GDP, income, investment, the deficit, monthly job gains. Stocks: the capital stock, wealth, the national debt, the number employed.",
      "Flows change stocks: investment adds to the capital stock, depreciation drains it; each year's deficit adds to the debt.",
    ],
    connections: ["gdp", "capital-accumulation", "unemployment-dynamics"],
    example: "Bathtub: the faucet's rate is the flow, the water in the tub is the stock. Your salary is a flow ($/year); your bank balance is a stock ($ on Dec 31).",
    numbers: [
      ["FY2025 deficit (flow)", "$1.8 trillion"],
      ["Debt held by public, FY2025 (stock)", "≈ 100% of GDP"],
    ],
    numbersSource: "CBO; CRFB estimate of debt at 99.8% of GDP.",
    played: [
      "Capital stock on Jan 1: 100 machines (stock).",
      "Investment during the year: +12 machines (flow). Depreciation: −5 (flow).",
      "Capital stock on Dec 31: 100 + 12 − 5 = 107.",
    ],
    graph: "stockFlow",
  },
  {
    id: "value-added", n: 9, week: W, tags: ["Ch 2", "BG"],
    term: "Value added",
    simple: "A firm's output minus what it paid for intermediate goods. GDP is the sum of value added across all firms.",
    formula: `value added${op("=")}value of output${op("−")}intermediate goods`,
    more: [
      "Summing value added at each stage gives exactly the value of the final good, which is why the value-added and final-goods methods give the same GDP.",
      "Value added is also the income created at that stage: wages and profit paid out of it.",
    ],
    connections: ["gdp", "expenditure-identity"],
    example: "A farmer sells wheat for $1, a miller turns it into flour for $3, a baker sells bread for $5. Value added: $1 + $2 + $2 = $5, the price of the bread.",
    played: [
      "Farmer: sells $1 of wheat, buys nothing → value added $1.",
      "Miller: sells flour for $3, paid $1 for wheat → $2.",
      "Baker: sells bread for $5, paid $3 for flour → $2.",
      "Sum: $5 = final sale. Adding every sale ($1 + $3 + $5 = $9) double counts the wheat and flour.",
    ],
    graph: "valueAdded",
  },
  {
    id: "nominal-gdp", n: 10, week: W, tags: ["Ch 2 #7"],
    term: "Nominal GDP",
    simple: "Output valued at <b>current</b> prices. It rises if prices rise or if quantities rise.",
    formula: `Nominal GDP<sub><i>t</i></sub>${op("=")}∑<sub><i>i</i></sub> <i>P</i><sub><i>i,t</i></sub><i>Q</i><sub><i>i,t</i></sub>`,
    more: [
      "Because it mixes price changes with real changes, nominal GDP alone can't tell you whether the economy produced more.",
      "Nominal GDP growth ≈ real GDP growth + inflation (of the GDP deflator).",
    ],
    connections: ["real-gdp", "gdp-deflator", "quantity-equation"],
    example: "If an economy makes the same 100 pizzas two years running but the price goes from $10 to $12, nominal GDP rises 20% from $1,000 to $1,200 while real output didn't change at all.",
    numbers: [
      ["Q2 2026 current-dollar GDP growth", "8.0% (annual rate)"],
      ["Q2 2026 real GDP growth", "2.2%"],
    ],
    numbersSource: "BEA second estimate (current dollars) and third estimate (real), 2026. The gap is mostly inflation.",
    played: [
      "Year 1: 100 pizzas at $10 + 50 books at $20 = $1,000 + $1,000 = $2,000.",
      "Year 2: 110 pizzas at $11 + 50 books at $22 = $1,210 + $1,100 = $2,310.",
      "Nominal GDP grew 15.5%, but some of that is just higher prices.",
    ],
  },
  {
    id: "real-gdp", n: 11, week: W, tags: ["Ch 2 #7"],
    term: "Real GDP",
    simple: "Output valued at <b>base-year</b> prices, so it changes only when quantities change.",
    formula: `Real GDP<sub><i>t</i></sub>${op("=")}∑<sub><i>i</i></sub> <i>P</i><sub><i>i</i>,base</sub><i>Q</i><sub><i>i,t</i></sub>`,
    more: [
      "Real GDP is what we use to measure growth and recessions. The US actually uses chain-weighting (the base year rolls forward every year) to limit the bias from a stale base year.",
    ],
    connections: ["nominal-gdp", "gdp-deflator", "recession"],
    example: "When the news says “the economy grew 2.2%” it means real GDP, at an annual rate. That was the Q2 2026 figure.",
    numbers: [
      ["Real GDP growth, Q2 2026", "2.2% (annual rate)"],
      ["Real GDP growth, Q1 2026", "2.5% (revised)"],
    ],
    numbersSource: "BEA, third estimate for Q2 2026 (Sep 30, 2026).",
    played: [
      "Use year 1 prices ($10 pizza, $20 book) for both years.",
      "Year 1: 100×$10 + 50×$20 = $2,000. Year 2: 110×$10 + 50×$20 = $2,100.",
      "Real GDP grew 5%. Compare nominal: 15.5%. The difference is inflation.",
    ],
  },
  {
    id: "gdp-deflator", n: 12, week: W, starred: true, tags: ["PE Q1", "Ch 2 #7"],
    term: "GDP deflator",
    simple: "The price of everything produced <b>domestically</b>: nominal GDP over real GDP, times 100.",
    formula: `GDP deflator${op("=")}${fr("Nominal GDP", "Real GDP")}${op("×")}100`,
    more: [
      "Its basket is whatever the economy produced this year, so it <b>changes every year</b> (a Paasche index).",
      "It <b>excludes imports</b> and includes things consumers never buy, like fighter jets, factory machines and government services.",
    ],
    connections: ["cpi", "cpi-vs-deflator", "laspeyres-paasche", "nominal-gdp", "real-gdp"],
    example: "If the price of US-made fighter jets rises, the deflator rises but the CPI doesn't (households don't buy jets). If the price of imported Toyotas rises, the CPI rises but the deflator doesn't.",
    played: [
      "From the pizza and book example: nominal GDP year 2 = $2,310; real GDP year 2 = $2,100.",
      "Deflator = 2,310 / 2,100 × 100 = 110.",
      "Prices of domestic output rose 10% since the base year.",
    ],
    graph: "indexBias",
  },
  {
    id: "cpi", n: 13, week: W, starred: true, tags: ["PE Q1", "Ch 2 #7"],
    term: "Consumer price index (CPI)",
    simple: "The price of a <b>fixed basket</b> of goods and services bought by a typical consumer, relative to a base year.",
    formula: `CPI<sub><i>t</i></sub>${op("=")}${fr("∑ <i>P</i><sub><i>i,t</i></sub><i>Q</i><sub><i>i</i>,base</sub>", "∑ <i>P</i><sub><i>i</i>,base</sub><i>Q</i><sub><i>i</i>,base</sub>")}${op("×")}100`,
    more: [
      "Fixed basket = a <b>Laspeyres</b> index. It <b>includes imports</b> consumers buy.",
      "BLS collects about 80,000 prices a month. Shelter (rent and owners' equivalent rent) is the biggest weight, roughly a third of the index.",
      "“Core” CPI drops food and energy because they're volatile.",
    ],
    connections: ["gdp-deflator", "cpi-vs-deflator", "laspeyres-paasche", "inflation-rate"],
    example: "Social Security benefits are raised every year by CPI inflation (the cost-of-living adjustment), so the CPI directly moves tens of millions of checks.",
    numbers: [
      ["CPI inflation, 12 months to Aug 2026", "3.4%"],
      ["Core CPI (ex food & energy)", "2.4%"],
      ["Energy prices", "+16.3%"],
      ["Peak of the 2021–23 surge (Jun 2022)", "9.1%"],
    ],
    numbersSource: "BLS CPI release, Sep 11, 2026; June 2022 peak, BLS.",
    played: [
      "Base-year basket: 10 apples at $1, 5 oranges at $2 → costs $20.",
      "This year: apples $2, oranges $2. Same basket costs 10×$2 + 5×$2 = $30.",
      "CPI = 30 / 20 × 100 = 150, so prices are 50% higher by this measure.",
    ],
    graph: "cpiHistory",
  },
  {
    id: "cpi-vs-deflator", n: 14, week: W, starred: true, tags: ["PE Q1"],
    term: "CPI vs GDP deflator (the tested difference)",
    simple: "The CPI includes imported goods and uses a fixed basket; the deflator includes only domestic production and its basket changes every year.",
    more: [
      "Both cover goods <b>and</b> services.",
      "Three differences to list on the exam: (1) <b>imports</b>: in CPI, not in deflator; (2) <b>investment and government goods</b>: in deflator, not in CPI; (3) <b>weights</b>: CPI's basket is fixed (Laspeyres), the deflator's changes (Paasche).",
    ],
    connections: ["cpi", "gdp-deflator", "laspeyres-paasche", "net-exports"],
    example: "When oil prices spike, the CPI jumps more than the deflator: much of the oil is imported, and gasoline is a big share of what consumers buy. In the 12 months to August 2026, energy prices were up 16.3% and headline CPI (3.4%) ran well above core (2.4%).",
    played: [
      "Year 2 quantities change: people buy 6 apples (now $2) and 8 oranges ($2) instead of 10 and 5.",
      "CPI uses the old basket: (10×2 + 5×2) / (10×1 + 5×2) = 30/20 → <b>150</b>.",
      "Deflator uses the new basket: (6×2 + 8×2) / (6×1 + 8×2) = 28/22 → <b>127</b>.",
      "Same prices, different weights: the CPI shows more inflation because it ignores the switch away from apples.",
    ],
    graph: "indexBias",
  },
  {
    id: "laspeyres-paasche", n: 15, week: W, tags: ["Ch 2 #7–8"],
    term: "Laspeyres vs Paasche bias",
    simple: "A fixed-basket index (CPI) <b>overstates</b> the rise in the cost of living; a changing-basket index (deflator) <b>understates</b> it.",
    more: [
      "Laspeyres (fixed basket) ignores <b>substitution</b>: when beef gets dearer people switch to chicken, but the index keeps buying beef.",
      "Paasche (current basket) gives the cheap goods people switched <i>toward</i> too much weight, so it misses part of the pain.",
      "The CPI has other upward biases too: new goods arrive late, and quality improvements look like price rises.",
    ],
    connections: ["cpi", "gdp-deflator", "cpi-vs-deflator"],
    example: "The 1996 Boskin Commission estimated that the CPI overstated inflation by about 1.1 percentage points a year. BLS has since added substitution and quality adjustments (and a chained CPI) to shrink the gap.",
    numbers: [
      ["Boskin Commission estimate of CPI overstatement (1996)", "≈ 1.1 pts/yr"],
    ],
    numbersSource: "Boskin Commission report to the Senate Finance Committee, 1996.",
    played: [
      "Same apples/oranges example: Laspeyres = 150, Paasche = 127.",
      "The true rise in the cost of staying equally happy lies between them.",
      "If benefits are indexed to the CPI, they rise a bit faster than the true cost of living.",
    ],
    graph: "indexBias",
  },
  {
    id: "inflation-rate", n: 16, week: W, tags: ["Ch 2"],
    term: "Inflation rate",
    simple: "The percentage change in a price index from one period to the next.",
    formula: `π<sub><i>t</i></sub>${op("=")}${fr("<i>P</i><sub><i>t</i></sub> − <i>P</i><sub><i>t</i>−1</sub>", "<i>P</i><sub><i>t</i>−1</sub>")}`,
    more: [
      "Use any index: CPI, GDP deflator, or the PCE price index (the one the Fed targets at 2%).",
      "Deflation is negative inflation; disinflation is inflation falling but still positive.",
    ],
    connections: ["cpi", "inflation", "fisher-equation", "qt-growth-rates"],
    example: "The 12-month CPI inflation rate was 3.4% in August 2026, above the Fed's 2% goal, one reason the Fed raised rates in September.",
    numbers: [
      ["CPI, 12 months to Aug 2026", "3.4%"],
      ["2022 annual average", "8.0%"],
      ["2024 annual average", "2.9%"],
    ],
    numbersSource: "BLS CPI-U.",
    played: [
      "CPI last year = 300, this year = 309.",
      "π = (309 − 300) / 300 = 9 / 300 = 0.03 → 3%.",
    ],
    graph: "cpiHistory",
  },
  {
    id: "labor-force", n: 17, week: W, tags: ["Ch 2 #9"],
    term: "Labor force",
    simple: "Everyone employed plus everyone unemployed.",
    formula: `<i>L</i>${op("=")}<i>E</i>${op("+")}<i>U</i>`,
    more: [
      "Measured from the household survey: adults 16+ not in prisons or other institutions, and not on active military duty.",
      "If you are neither working nor looking, you're <b>outside</b> the labor force.",
    ],
    connections: ["unemployed", "not-in-lf", "unemployment-rate", "lfpr"],
    example: "A college student with no job who isn't looking is not in the labor force. The same student working 5 hours a week at the library is employed and in the labor force.",
    numbers: [
      ["US unemployed, Sep 2026", "7.1 million"],
      ["Unemployment rate, Sep 2026", "4.2%"],
      ["Implied labor force (7.1M ÷ 0.042)", "≈ 169 million"],
    ],
    numbersSource: "BLS Employment Situation, Oct 2, 2026; labor force implied from the two published figures.",
    graph: "laborForceTree",
  },
  {
    id: "unemployed", n: 18, week: W, tags: ["Ch 2 #9"],
    term: "Unemployed",
    simple: "Without a job, available to work, and actively searching (in the past four weeks).",
    more: [
      "All three conditions must hold. Not searching = not in the labor force, even if you'd like a job.",
      "People on temporary layoff waiting to be recalled count as unemployed even if they aren't searching.",
    ],
    connections: ["labor-force", "unemployment-rate", "discouraged", "not-in-lf"],
    example: "A laid-off engineer who sent out applications last week: unemployed. One who gave up searching three months ago: not in the labor force.",
    numbers: [
      ["Unemployed, Sep 2026", "7.1 million"],
    ],
    numbersSource: "BLS Employment Situation, Oct 2, 2026.",
    graph: "laborForceTree",
  },
  {
    id: "not-in-lf", n: 19, week: W, tags: ["Ch 2 #9"],
    term: "Not in the labor force",
    simple: "Adults who are neither working nor looking for work: retirees, students, homemakers and discouraged workers.",
    more: [
      "Movements in and out of this group change the unemployment rate without anything happening to jobs, which is why economists also watch the employment-population ratio.",
    ],
    connections: ["labor-force", "discouraged", "lfpr", "epop", "unemployment-imperfect"],
    example: "Baby boomers retiring in large numbers since about 2010 have pulled the overall participation rate down, even though prime-age (25–54) participation is near record highs.",
    numbers: [
      ["Prime-age (25–54) participation, Aug 2026", "83.4%"],
    ],
    numbersSource: "BLS via FRED (LNS11300060).",
    graph: "laborForceTree",
  },
  {
    id: "discouraged", n: 20, week: W, starred: true, tags: ["PE Q3", "Ch 2 #9"],
    term: "Discouraged worker",
    simple: "Someone who wants a job but has stopped searching because they think none is available. Counted as <b>not in the labor force</b>, not as unemployed.",
    more: [
      "This is the classic reason the unemployment rate understates labor-market weakness: when job seekers give up, U falls and so does the measured rate.",
      "BLS's broader U-4 to U-6 measures add discouraged and other marginally attached workers back in.",
    ],
    connections: ["unemployed", "not-in-lf", "unemployment-imperfect", "unemployment-rate"],
    example: "After a plant closes in a small town, a 55-year-old machinist searches for a year, finds nothing, and stops. The next month the town's unemployment rate falls, although no one found a job.",
    played: [
      "Start: E = 90, U = 10 → u = 10 / 100 = 10%.",
      "2 unemployed people give up: E = 90, U = 8, L = 98.",
      "u = 8 / 98 = 8.2%. The rate fell 1.8 points, yet employment didn't change.",
    ],
    graph: "laborForceTree",
  },
  {
    id: "unemployment-rate", n: 21, week: W, tags: ["Ch 2 #9"],
    term: "Unemployment rate",
    simple: "The share of the labor force that is unemployed.",
    formula: `<i>u</i>${op("=")}${fr("<i>U</i>", "<i>L</i>")}${op("=")}${fr("<i>U</i>", "<i>E</i> + <i>U</i>")}`,
    more: [
      "The denominator is the <b>labor force</b>, not the whole population. That's the most common mistake.",
    ],
    connections: ["labor-force", "unemployed", "natural-rate", "ss-unemployment-rate", "unemployment-imperfect"],
    example: "The September 2026 jobs report: 4.2%, inside the narrow 4.1–4.3% range it had held since March.",
    numbers: [
      ["Sep 2026", "4.2%"],
      ["Oct 2009 (Great Recession peak)", "10.0%"],
      ["Apr 2020 (COVID)", "14.8%"],
    ],
    numbersSource: "BLS.",
    played: [
      "E = 160 million, U = 7 million.",
      "L = 167 million.",
      "u = 7 / 167 = 4.2%.",
    ],
    graph: "laborForceTree",
  },
  {
    id: "lfpr", n: 22, week: W, tags: ["Ch 2 #9"],
    term: "Labor force participation rate",
    simple: "The share of the adult population that is in the labor force (working or looking).",
    formula: `LFPR${op("=")}${fr("<i>L</i>", "adult population")}`,
    more: [
      "Long-run US trends: women's participation climbed from the 1950s to about 2000; the overall rate has drifted down since 2000 mostly because the population is aging.",
    ],
    connections: ["labor-force", "epop", "not-in-lf"],
    example: "Two economies can have the same 4% unemployment rate but very different participation: one where 70% of adults are in the labor force and one where 60% are.",
    numbers: [
      ["US overall, 2025", "≈ 62%"],
      ["Prime-age 25–54, Aug 2026", "83.4%"],
    ],
    numbersSource: "BLS (overall rate, approximate 2025 level); FRED LNS11300060.",
    played: [
      "Adult population 270M; labor force 168M.",
      "LFPR = 168 / 270 = 62.2%.",
    ],
    graph: "laborForceTree",
  },
  {
    id: "epop", n: 23, week: W, tags: ["L2"],
    term: "Employment-population ratio",
    simple: "The share of all adults who have a job.",
    formula: `${fr("<i>E</i>", "adult population")}`,
    more: [
      "Its advantage: it is <b>not affected</b> by people moving between unemployment and out of the labor force, because neither group is in the numerator, and the denominator (all adults) doesn't change.",
      "That makes it a cleaner gauge of jobs when lots of people are giving up or returning to search.",
    ],
    connections: ["lfpr", "unemployment-rate", "discouraged", "unemployment-imperfect"],
    example: "In the discouraged-worker example the unemployment rate fell from 10% to 8.2%, but the employment-population ratio didn't move at all. It correctly says nothing improved.",
    numbers: [
      ["US, 2025", "≈ 60%"],
    ],
    numbersSource: "BLS, approximate 2025 level.",
    played: [
      "Adults = 150, E = 90, U = 10 → E/pop = 60%.",
      "2 unemployed give up: E still 90, adults still 150 → still 60%.",
      "Unemployment rate fell; the employment-population ratio correctly didn't.",
    ],
    graph: "laborForceTree",
  },
  {
    id: "household-vs-establishment", n: 24, week: W, tags: ["Ch 2 #9c"],
    term: "Household survey vs establishment survey",
    simple: "The <b>household</b> survey counts <i>people</i> employed (it gives the unemployment rate). The <b>establishment</b> (payroll) survey counts <i>jobs</i>.",
    more: [
      "Payroll survey: someone with two jobs counts <b>twice</b>; the self-employed, farm workers and household workers are <b>not counted</b>.",
      "The payroll survey's monthly “jobs added” is the headline number; it has a much larger sample, so it is less noisy month to month.",
    ],
    connections: ["unemployment-rate", "labor-force", "stock-flow"],
    example: "In the September 2026 report the payroll survey showed just +29,000 jobs while the household survey's unemployment rate held at 4.2%. The two often disagree in any single month.",
    numbers: [
      ["Household survey (CPS)", "≈ 60,000 households"],
      ["Payroll survey (CES)", "≈ 121,000 businesses & agencies"],
      ["Payroll change, Sep 2026", "+29,000"],
    ],
    numbersSource: "BLS survey descriptions; Employment Situation, Oct 2, 2026 (payroll figure preliminary).",
    played: [
      "Maria drives for Uber (self-employed) and works part-time at Target.",
      "Household survey: 1 employed person.",
      "Payroll survey: 1 job (Target only; Uber driving is self-employment).",
    ],
  },
  {
    id: "gdp-wellbeing", n: 25, week: W, tags: ["Ch 2 #10–11"],
    term: "GDP and well-being",
    simple: "GDP misses leisure, home production, health and the environment, and can rise with things that make life worse. It's still useful because it moves with much of what people value.",
    more: [
      "Missing: unpaid work (childcare, cooking), leisure, pollution, inequality, the underground economy.",
      "Perverse cases: rebuilding after a hurricane, or more spending on security after a crime wave, both raise GDP.",
      "Still, richer countries have longer life expectancy, more education and lower child mortality, so GDP per person is a good rough guide.",
    ],
    connections: ["gdp", "income-wellbeing", "solow"],
    example: "If you hire a cleaner instead of cleaning your own home, GDP rises even though the same work gets done. If you take an unpaid month off, GDP falls though you may be better off.",
  },
];
