import { fr, op } from "./helpers.mjs";

const W = 3;

export default [
  {
    id: "inflation", n: 60, week: W, tags: ["Ch 6 key concept"],
    term: "Inflation",
    simple: "A sustained increase in the overall level of prices.",
    more: [
      "<b>Sustained</b> and <b>overall</b>: a one-time jump in the price of eggs is a relative-price change, not inflation. Inflation is when the general price level keeps rising, so money keeps losing purchasing power.",
      "Milton Friedman: “Inflation is always and everywhere a monetary phenomenon”, in the long run, the quantity theory.",
    ],
    connections: ["inflation-rate", "quantity-theory", "hyperinflation", "recent-inflation"],
    example: "$1 in 1990 bought about what $2.45 buys today. Prices more than doubled over 35 years at an average inflation rate of about 2.5% a year.",
    numbers: [
      ["CPI inflation, 12 mo. to Aug 2026", "3.4%"],
      ["Fed's target (PCE inflation)", "2%"],
    ],
    numbersSource: "BLS; Federal Reserve.",
    graph: "cpiHistory",
  },
  {
    id: "hyperinflation", n: 61, week: W, tags: ["Ch 6 key concept", "L5", "BG"],
    term: "Hyperinflation",
    simple: "Extremely high inflation (Mankiw: above 50% per month). It starts when governments print money to pay for big deficits and ends with fiscal reform.",
    more: [
      "Cause: a government that can't borrow or tax enough prints money (seigniorage). Prices rise, the real value of its tax revenue falls, it prints faster: a spiral.",
      "Cure: <b>fiscal</b> reform that removes the need for seigniorage, usually with a new currency or central-bank independence. A new currency alone doesn't work if the deficits continue.",
    ],
    connections: ["seigniorage", "inflation-tax", "quantity-theory", "shoeleather"],
    example: "Germany 1922–23: in November 1923 a US dollar cost 4.2 trillion paper marks (it had cost 4.2 marks in 1914). Workers were paid twice a day and rushed to spend before prices rose again. The Rentenmark, swapped at 1 for 1 trillion old marks, plus budget cuts, ended it.",
    numbers: [
      ["Germany, marks per $ (1914)", "4.2"],
      ["Germany, marks per $ (Nov 1923)", "4.2 trillion"],
      ["Zimbabwe, monthly inflation (Nov 2008)", "≈ 79.6 billion %"],
      ["Hungary 1946: prices doubled every", "≈ 15 hours"],
    ],
    numbersSource: "Historical exchange-rate data for the Weimar mark; Hanke & Krus, World Hyperinflations (2012) for Zimbabwe and Hungary.",
    played: [
      "50% per month compounds: 1.5<sup>12</sup> ≈ 130.",
      "So prices rise about 13,000% in a year at the threshold rate.",
    ],
    graph: "hyperinflation",
  },
  {
    id: "money", n: 62, week: W, tags: ["BG (Lecture 6 not in files)"],
    term: "Money",
    simple: "The stock of assets used for transactions. It serves as a store of value, a unit of account and a medium of exchange.",
    more: [
      "<b>Medium of exchange</b>: what you hand over to buy things (avoids barter's double coincidence of wants). <b>Unit of account</b>: what prices are quoted in. <b>Store of value</b>: carries purchasing power into the future (imperfectly, if there's inflation).",
      "Fiat money (dollars) has no intrinsic value; commodity money (gold coins, cigarettes in POW camps) does.",
    ],
    connections: ["m1", "monetary-base", "real-money-balances", "money-demand"],
    example: "In WWII prisoner-of-war camps, cigarettes became money: prices of food and clothing were quoted in cigarettes, even by non-smokers.",
    numbers: [
      ["US M2, Jul 2026", "$23.2 trillion"],
      ["US M1, Feb 2026", "≈ $19.4 trillion"],
    ],
    numbersSource: "Federal Reserve H.6 (M2 release of Aug 25, 2026; M1 via Trading Economics).",
    graph: "moneyAggregates",
  },
  {
    id: "quantity-equation", n: 63, week: W, tags: ["Ch 6 key concept", "PS3"],
    term: "Quantity equation",
    simple: "Money times velocity equals nominal GDP.",
    formula: `<i>M</i>${op("×")}<i>V</i>${op("=")}<i>P</i>${op("×")}<i>Y</i>`,
    more: [
      "By itself it's an <b>identity</b>: V is defined as PY/M, so it always holds. It becomes a theory (the quantity theory) once you assume V is constant.",
    ],
    connections: ["velocity", "quantity-theory", "qt-growth-rates", "nominal-gdp"],
    example: "If the Fed doubles M and velocity and real output don't change, nominal GDP must double, and the only way is for P to double.",
    played: [
      "US 2025: PY ≈ $30.8 trillion; M2 ≈ $22 trillion.",
      "V = 30.8 / 22 ≈ <b>1.4</b>: each dollar of M2 funds about $1.40 of final spending a year.",
    ],
    graph: "quantityTheory",
  },
  {
    id: "transactions-income-velocity", n: 64, week: W, tags: ["Ch 6 key concept"],
    term: "Transactions vs income velocity",
    simple: "Transactions velocity uses all transactions: MV = PT. Income velocity uses output: MV = PY. The course uses income velocity.",
    more: [
      "Transactions include used goods, intermediate goods and financial trades, which are hard to measure. Output (Y) is in the national accounts, so income velocity is what people actually compute.",
    ],
    connections: ["quantity-equation", "velocity"],
    example: "Buying a used car is a transaction (in T) but not output (not in Y), so it affects transactions velocity only.",
  },
  {
    id: "velocity", n: 65, week: W, starred: true, tags: ["PE Q11", "Ch 6 #3"],
    term: "Velocity of money",
    simple: "How many times a dollar changes hands in a period.",
    formula: `<i>V</i>${op("=")}${fr("<i>PY</i>", "<i>M</i>")}`,
    more: [
      "Velocity rises when people hold less money relative to spending, for instance when interest rates are high (holding cash costs more) or when payment technology improves.",
      "M2 velocity fell sharply in 2020 when people piled up deposits during lockdowns.",
    ],
    connections: ["quantity-equation", "money-demand", "quantity-theory"],
    example: "Picture a $20 bill that pays for a haircut, then the barber's lunch, then the cook's gas, all in a week: that one bill financed $60 of spending.",
    numbers: [
      ["US nominal GDP, 2025", "≈ $30.8 trillion"],
      ["M2 (2025 average, approx.)", "≈ $22 trillion"],
      ["Implied M2 velocity", "≈ 1.4"],
    ],
    numbersSource: "BEA; Federal Reserve H.6. Velocity computed here as PY/M.",
    played: [
      "Nominal GDP = $600, M = $200.",
      "V = 600 / 200 = 3. Each dollar is spent 3 times a year on final goods.",
    ],
    graph: "quantityTheory",
  },
  {
    id: "real-money-balances", n: 66, week: W, tags: ["Ch 6 key concept"],
    term: "Real money balances",
    simple: "The purchasing power of the money stock: money divided by the price level.",
    formula: `${fr("<i>M</i>", "<i>P</i>")}`,
    more: [
      "It measures money in units of goods. If M doubles and P doubles, real balances are unchanged.",
    ],
    connections: ["money-demand", "inflation-tax", "real-nominal"],
    example: "$100 in your wallet when a burger costs $10 is 10 burgers of real balances. If burger prices double, it's 5.",
    played: [
      "M = $1,000, P = 2 → M/P = 500 units of goods.",
      "Inflation of 10% with M unchanged: M/P = 1,000 / 2.2 = 455.",
    ],
    graph: "moneyDemand",
  },
  {
    id: "money-demand", n: 67, week: W, tags: ["Ch 6 #2–4"],
    term: "Money demand function",
    simple: "People want real money balances in proportion to income; more generally, demand falls as the nominal interest rate rises.",
    formula: `(${fr("<i>M</i>", "<i>P</i>")})<sup><i>d</i></sup>${op("=")}<i>kY</i>${op("⇒")}<i>V</i>${op("=")}${fr("1", "<i>k</i>")}`,
    more: [
      "General form: (M/P)<sup>d</sup> = L(i, Y). Money pays no interest, so the nominal rate <i>i</i> is the opportunity cost of holding it. Higher i means lower money demand, so <b>velocity rises with i</b>.",
      "Uses the <b>nominal</b> rate: holding cash instead of a bond loses the real return plus the inflation that eats the cash.",
    ],
    connections: ["real-money-balances", "velocity", "nominal-real-rate", "shoeleather"],
    example: "When savings accounts paid near 0% in 2020–21, people left lots of money in checking. When yields rose to 4–5% in 2023, money flowed out of checking into money-market funds and Treasury bills.",
    played: [
      "k = 0.25, Y = 400 → (M/P)<sup>d</sup> = 100.",
      "V = 1/k = 4.",
    ],
    graph: "moneyDemand",
  },
  {
    id: "quantity-theory", n: 68, week: W, starred: true, tags: ["PE Q15", "Ch 6 key concept"],
    term: "Quantity theory of money",
    simple: "With velocity constant and output fixed by factors of production, the money supply determines nominal GDP and the price level: P is proportional to M.",
    formula: `<i>M V̅</i>${op("=")}<i>P Y̅</i>${op("⇒")}<i>P</i>${op("=")}${fr("<i>V̅</i>", "<i>Y̅</i>")}<i>M</i>`,
    more: [
      "Three pieces: (1) factors and technology fix Y; (2) money supply M fixes nominal GDP PY via constant V; (3) so P = PY / Y.",
      "Good long-run theory; it fails in the short run because V moves a lot.",
    ],
    connections: ["quantity-equation", "qt-growth-rates", "classical-dichotomy", "seigniorage"],
    example: "Spain in the 1500s: silver and gold shipped in from the Americas expanded the money supply, and prices across Europe rose about fourfold over the following century (the “price revolution”).",
    played: [
      "V = 4, Y = 400, M = 100 → P = (4/400) × 100 = 1.",
      "Double M to 200 → P = 2. Y unchanged. Only prices changed.",
    ],
    graph: "quantityTheory",
  },
  {
    id: "qt-growth-rates", n: 69, week: W, tags: ["Ch 6 #1", "PS3"],
    term: "Quantity theory in growth rates",
    simple: "Money growth plus velocity growth equals inflation plus real growth. With constant velocity, inflation is money growth minus output growth.",
    formula: `%Δ<i>M</i> + %Δ<i>V</i>${op("=")}%Δ<i>P</i> + %Δ<i>Y</i><br>π${op("=")}%Δ<i>M</i>${op("−")}%Δ<i>Y</i>`,
    more: [
      "Take logs of MV = PY and differentiate: growth rates add.",
    ],
    connections: ["quantity-theory", "inflation-rate", "classical-combined"],
    example: "M2 grew 5.4% in the year to July 2026. If real GDP grows about 2% and velocity holds still, the theory implies inflation around 3.4%, close to the 3.4% CPI reading for August.",
    numbers: [
      ["M2 growth, 12 mo. to Jul 2026", "5.4%"],
      ["CPI inflation, 12 mo. to Aug 2026", "3.4%"],
    ],
    numbersSource: "Federal Reserve H.6; BLS. The close match is partly luck: velocity isn't really constant year to year.",
    played: [
      "%ΔM = 5%, %ΔY = 2%, %ΔV = 0.",
      "π = 5 − 2 = <b>3%</b>.",
    ],
    graph: "quantityTheory",
  },
  {
    id: "seigniorage", n: 70, week: W, starred: true, tags: ["PE Q15", "Ch 6 key concept"],
    term: "Seigniorage",
    simple: "Revenue the government raises by printing money.",
    more: [
      "Printing money to pay bills is one of three ways to finance spending (with taxes and borrowing). It's small in the US but has been the main revenue source in every hyperinflation.",
      "The word comes from the feudal lord (seigneur) who had the right to mint coins and keep the difference between face value and metal cost.",
    ],
    connections: ["inflation-tax", "hyperinflation", "quantity-theory", "monetary-base"],
    example: "The Fed earns interest on the bonds it bought with newly created money and sends the profit to the Treasury: a modern form of seigniorage.",
    numbers: [
      ["Fed remittances to Treasury, 2021", "$107 billion"],
      ["Since late 2022", "losses booked as a “deferred asset”"],
    ],
    numbersSource: "Federal Reserve annual financial statements.",
  },
  {
    id: "inflation-tax", n: 71, week: W, starred: true, tags: ["PE Q15"],
    term: "Inflation tax",
    simple: "Printing money causes inflation, so money people hold loses value while the government gains revenue. It works like a tax on <b>people who hold money</b>.",
    formula: `inflation tax${op("≈")}π${op("×")}${fr("<i>M</i>", "<i>P</i>")}`,
    more: [
      "Nobody gets a tax bill; the tax is collected through rising prices that shrink the real value of cash.",
      "It falls hardest on people who hold a lot of cash relative to income, often the poor and unbanked.",
    ],
    connections: ["seigniorage", "real-money-balances", "hyperinflation", "unexpected-inflation"],
    example: "If you keep $1,000 under your mattress for a year of 10% inflation, it buys about $909 worth of goods at the end. The government, which printed the money, captured the $91.",
    played: [
      "Real balances M/P = $500, inflation π = 4%.",
      "Inflation tax ≈ 0.04 × 500 = $20 of purchasing power a year.",
    ],
  },
  {
    id: "nominal-real-rate", n: 72, week: W, tags: ["Ch 6 key concept"],
    term: "Nominal vs real interest rate",
    simple: "The nominal rate <i>i</i> is what the bank pays. The real rate <i>r</i> is the increase in your purchasing power.",
    formula: `<i>r</i>${op("=")}<i>i</i>${op("−")}π`,
    more: [
      "Real rate is what matters for saving and investment decisions; the nominal rate is what matters for money demand.",
    ],
    connections: ["fisher-equation", "ex-ante-post", "investment-function", "money-demand"],
    example: "A savings account paying 4% when inflation is 3.4% gives a real return of only 0.6%.",
    numbers: [
      ["Fed funds target (from Sep 17, 2026)", "3.75–4.00%"],
      ["CPI inflation, Aug 2026", "3.4%"],
      ["Rough real policy rate", "≈ +0.5%"],
    ],
    numbersSource: "Federal Reserve FOMC statement, Sep 16, 2026; BLS.",
    graph: "inflationVsRates",
  },
  {
    id: "fisher-equation", n: 73, week: W, tags: ["PS3", "Ch 6 #1"],
    term: "Fisher equation",
    simple: "The nominal interest rate equals the real rate plus inflation.",
    formula: `<i>i</i>${op("=")}<i>r</i>${op("+")}π`,
    more: [
      "Named for Irving Fisher. In the classical model r comes from the loanable-funds market and π from money growth; the Fisher equation stitches them together.",
    ],
    connections: ["fisher-effect", "nominal-real-rate", "classical-combined"],
    played: [
      "r = 2%, π = 3% → i = 5%.",
    ],
    graph: "fisher",
  },
  {
    id: "fisher-effect", n: 74, week: W, tags: ["Ch 6 #3d", "Ch 6 key concept", "L5"],
    term: "Fisher effect",
    simple: "A one-point rise in expected inflation raises the nominal interest rate by one point and leaves the real rate unchanged.",
    more: [
      "Lenders demand compensation for the purchasing power they expect to lose; borrowers are willing to pay it because they'll repay in cheaper dollars.",
      "Holds well across countries and across decades; much less well month to month.",
    ],
    connections: ["fisher-equation", "qt-growth-rates", "ex-ante-post"],
    example: "In 1980–81 US CPI inflation ran in the low teens and the fed funds rate went as high as about 20%. In 2021 inflation and rates were both near zero at the start of the year. High-inflation countries like Argentina and Turkey have had double- or triple-digit interest rates.",
    played: [
      "Money growth rises 2 points → π rises 2 points (quantity theory).",
      "r is fixed by the real side (S = I(r)).",
      "So i rises 2 points: 5% → 7%.",
    ],
    graph: "fisher",
  },
  {
    id: "ex-ante-post", n: 75, week: W, tags: ["Ch 6 key concept"],
    term: "Ex ante vs ex post real interest rate",
    simple: "Ex ante uses <b>expected</b> inflation (what you anticipate when lending); ex post uses <b>actual</b> inflation (what really happened).",
    formula: `<i>r</i><sup>ex ante</sup>${op("=")}<i>i</i>${op("−")}<i>E</i>[π]<span style="display:inline-block;width:14px"></span><i>r</i><sup>ex post</sup>${op("=")}<i>i</i>${op("−")}π`,
    more: [
      "Nominal rates are set using expected inflation: <i>i = r + E[π]</i>. When inflation surprises, the ex post real rate differs from the ex ante one, and that's where the redistribution from unexpected inflation comes from.",
      "Inflation-protected bonds (TIPS) pay a real rate directly, so their yields are a market read on ex ante real rates.",
    ],
    connections: ["fisher-equation", "unexpected-inflation", "nominal-real-rate"],
    example: "Someone who locked in a 3% mortgage in 2020 expecting about 2% inflation (ex ante real rate +1%) then lived through 8% inflation in 2022: an ex post real rate of −5% that year. Great for the borrower, bad for the lender.",
    played: [
      "i = 5%, expected π = 2% → ex ante r = 3%.",
      "Actual π = 6% → ex post r = −1%.",
      "The lender expected to gain 3% in purchasing power and lost 1%.",
    ],
  },
  {
    id: "shoeleather", n: 76, week: W, tags: ["Ch 6 key concept", "Ch 6 #7"],
    term: "Shoeleather costs",
    simple: "The costs of holding less money because of inflation, such as more trips to the bank.",
    more: [
      "High inflation raises the nominal interest rate, so people hold less cash and make more frequent withdrawals, wearing out their shoes (metaphorically). Today it's time and hassle.",
      "Small at moderate inflation, huge in hyperinflation.",
    ],
    connections: ["money-demand", "menu-costs", "other-costs", "hyperinflation"],
    example: "During Germany's 1923 hyperinflation, workers were paid twice a day and family members rushed to shops at lunchtime to spend the morning's wages before prices rose again.",
  },
  {
    id: "menu-costs", n: 77, week: W, tags: ["Ch 6 key concept", "Ch 6 #7"],
    term: "Menu costs",
    simple: "The costs of changing prices, such as reprinting catalogs and menus.",
    more: [
      "Includes the time spent deciding on new prices and the risk of annoying customers. Higher inflation means prices must be changed more often.",
      "Because firms change prices infrequently, prices get out of line with each other: the relative-price variability on the next card.",
    ],
    connections: ["shoeleather", "other-costs"],
    example: "Coca-Cola kept the price of a bottle at 5 cents from 1886 to 1959, partly because vending machines only took nickels: changing the price meant re-engineering every machine.",
  },
  {
    id: "other-costs", n: 78, week: W, tags: ["Ch 6 #5, #7"],
    term: "Other costs of expected inflation",
    simple: "Relative prices get out of line, nominal gains get taxed, and a changing unit of account makes planning harder.",
    more: [
      "<b>Relative-price variability</b>: prices change at different times, so resources are misallocated.",
      "<b>Tax distortions</b>: taxes are on nominal gains, so inflation alone can create a tax bill on an asset that didn't gain in real terms.",
      "<b>Inconvenience</b>: a dollar is a different-sized ruler each year, which makes long-term contracts and accounting harder.",
    ],
    connections: ["shoeleather", "menu-costs", "real-nominal"],
    played: [
      "Buy a stock for $100. Ten years later prices have risen 30%; sell for $130.",
      "Real gain: zero. Taxable gain: $30.",
      "At a 20% rate you pay $6 tax and end up with less purchasing power than you started with.",
    ],
  },
  {
    id: "unexpected-inflation", n: 79, week: W, tags: ["Ch 6 #7b"],
    term: "Cost of unexpected inflation",
    simple: "Arbitrary redistribution between debtors and creditors. Lenders with fixed nominal payments lose; borrowers gain.",
    more: [
      "Contracts in nominal terms (loans, pensions, annuities, wage contracts) bake in expected inflation. Surprise inflation shifts real wealth from whoever receives fixed dollars to whoever pays them.",
      "Surprise <i>deflation</i> runs the other way: borrowers lose.",
    ],
    connections: ["ex-ante-post", "inflation-tax", "fisher-equation"],
    example: "A retiree with a fixed $2,000-a-month annuity lost about 8% of its purchasing power in 2022 alone. Homeowners with fixed-rate mortgages gained: their payments stayed the same while their incomes rose with inflation.",
    played: [
      "Bank lends $100 at 5% expecting 2% inflation (real 3%).",
      "Actual inflation 7%. Repayment $105 buys what $98 bought a year ago.",
      "The bank lost 2% in real terms; the borrower gained it.",
    ],
  },
  {
    id: "benefit-inflation", n: 80, week: W, tags: ["Ch 6"],
    term: "Possible benefit of inflation",
    simple: "Lets real wages fall without nominal wage cuts, and allows negative real interest rates.",
    more: [
      "Workers strongly resist nominal pay cuts. With 2–3% inflation, a firm can cut a real wage by just not giving a raise (“greasing the wheels” of the labor market).",
      "With some inflation, a 0% nominal rate is a negative real rate, giving the central bank room to stimulate in a recession.",
      "One reason central banks target 2% rather than 0%.",
    ],
    connections: ["real-wage", "wage-rigidity", "nominal-real-rate"],
    example: "In 2020–21 the Fed held the funds rate near 0% while inflation rose; real rates were sharply negative, encouraging borrowing and spending.",
  },
  {
    id: "real-nominal", n: 81, week: W, starred: true, tags: ["Ch 6 key concept", "PE Q20"],
    term: "Real vs nominal variables",
    simple: "<b>Nominal</b> variables are measured in money (prices, nominal wages, i). <b>Real</b> variables are measured in physical units (output, the real wage, r).",
    more: [
      "Real variables: Y, C, I, real wage W/P, real rental R/P, r, M/P, employment.",
      "Nominal variables: P, W, R, i, M, nominal GDP.",
    ],
    connections: ["classical-dichotomy", "monetary-neutrality", "real-money-balances"],
    example: "Your salary going from $50,000 to $52,000 is a nominal change. Whether you can afford more groceries depends on the real change.",
    played: [
      "Nominal wage $30, price level 1.5 → real wage = 20 (in base-year dollars).",
    ],
  },
  {
    id: "classical-dichotomy", n: 82, week: W, starred: true, tags: ["PE Q20", "Ch 6 key concept"],
    term: "Classical dichotomy",
    simple: "The theoretical separation of real and nominal variables: <b>nominal variables do not affect real variables</b>.",
    more: [
      "Real variables are determined by the real side (factors, technology, saving, investment). Money only sets nominal variables.",
      "<b>The reverse is false</b>: real variables do affect nominal ones. A rise in Y, for instance, lowers P in the quantity theory. That reversal is a classic true/false trap.",
    ],
    connections: ["monetary-neutrality", "real-nominal", "quantity-theory", "classical-combined"],
    example: "Cutting six zeros off every price and wage overnight (as Turkey did in 2005, turning 1,000,000 old lira into 1 new lira) changes nothing real: same output, same jobs, same real wages.",
  },
  {
    id: "monetary-neutrality", n: 83, week: W, tags: ["Ch 6 key concept"],
    term: "Monetary neutrality",
    simple: "Changes in the money supply do not affect real variables in the long run.",
    more: [
      "The classical dichotomy applied to money. Most economists accept it in the long run; in the short run (later chapters) sticky prices let money affect output and jobs.",
    ],
    connections: ["classical-dichotomy", "quantity-theory", "real-nominal"],
    played: [
      "M doubles. Long run: P doubles, W doubles, nominal GDP doubles.",
      "Y, W/P, r, employment: unchanged.",
    ],
    graph: "quantityTheory",
  },
  {
    id: "monetary-base", n: 84, week: W, starred: true, tags: ["PE Q16c"],
    term: "Monetary base",
    simple: "Currency in circulation plus bank reserves. <b>Not</b> the sum of all currency and deposits.",
    formula: `<i>B</i>${op("=")}<i>C</i>${op("+")}<i>R</i>`,
    more: [
      "It's the money the Fed directly creates: cash in the public's hands plus the deposits banks hold at the Fed (reserves).",
      "Deposits in your checking account are in M1, not in the base. That distinction is what PE Q16c tests.",
    ],
    connections: ["m1", "omo", "seigniorage", "money"],
    example: "When the Fed buys a Treasury bond from a bank, it pays by crediting the bank's reserve account: the monetary base rises instantly.",
    numbers: [
      ["US currency in circulation (2025, approx.)", "≈ $2.4 trillion"],
    ],
    numbersSource: "Federal Reserve, approximate.",
    graph: "moneyAggregates",
  },
  {
    id: "m1", n: 85, week: W, starred: true, tags: ["PE Q16b", "PS2"],
    term: "M1",
    simple: "Currency plus checkable deposits. Since a 2020 Fed rule change it also includes savings deposits, which caused an artificial jump in measured M1.",
    more: [
      "In May 2020 the Fed reclassified savings deposits as “transaction accounts” (it had removed the six-withdrawals-a-month limit). Measured M1 roughly tripled overnight from about $4.9 trillion to about $16 trillion, without any new money being created.",
      "M2 = M1 + small time deposits + retail money-market funds.",
    ],
    connections: ["monetary-base", "money", "velocity"],
    example: "The 2020 jump is a measurement break, not a policy action: always check definitions before reading a chart.",
    numbers: [
      ["M1, Apr 2020", "≈ $4.9 trillion"],
      ["M1, May 2020 (after reclassification)", "≈ $16 trillion"],
      ["M1, Feb 2026", "≈ $19.4 trillion"],
    ],
    numbersSource: "Federal Reserve H.6 (approximate levels).",
    graph: "moneyAggregates",
  },
  {
    id: "omo", n: 86, week: W, starred: true, tags: ["PE Q16d"],
    term: "Open market operations",
    simple: "The Fed changes the money supply by buying or selling assets such as short-term government debt.",
    more: [
      "<b>Buy</b> bonds → pays with new reserves → money supply up, interest rates down. <b>Sell</b> bonds → absorbs reserves → money supply down, rates up.",
      "Today the Fed mainly steers rates with administered rates (interest on reserve balances), but open market operations are still how it changes the size of its balance sheet (QE and QT).",
    ],
    connections: ["monetary-base", "fed-funds", "forward-guidance"],
    example: "Quantitative easing in 2008–14 and 2020–22 was open market purchases on a huge scale: the Fed bought trillions of dollars of Treasuries and mortgage-backed securities.",
    played: [
      "Fed buys $1 billion of T-bills from a bank.",
      "Bank's bonds −$1B, its reserves at the Fed +$1B.",
      "Monetary base +$1B; banks can lend more.",
    ],
  },
  {
    id: "forward-guidance", n: 87, week: W, starred: true, tags: ["PE Q2"],
    term: "Forward guidance",
    simple: "The Fed giving information about its expected future policy. It keeps the economy stable by anchoring expectations about future inflation.",
    more: [
      "Because long-term interest rates depend on expected future short rates, telling markets what the Fed plans moves long rates today.",
      "Works only if it's credible: the Fed has to follow through.",
    ],
    connections: ["fed-funds", "omo", "ex-ante-post"],
    example: "In August 2011 the Fed said it expected to keep rates exceptionally low “at least through mid-2013”. Long-term Treasury yields fell immediately, though the Fed hadn't changed the rate that day.",
  },
  {
    id: "fed-funds", n: 88, week: W, tags: ["L5"],
    term: "Federal funds rate",
    simple: "The overnight interest rate banks charge each other for reserves. The FOMC sets a target range for it.",
    more: [
      "The Federal Open Market Committee meets eight times a year. It moves the rate into its target range mainly by setting the interest rate on reserve balances (IORB).",
    ],
    connections: ["omo", "forward-guidance", "nominal-real-rate", "recent-inflation"],
    example: "On September 16, 2026 the FOMC raised the target by a quarter point to 3.75–4.00% by a 12–0 vote, its first hike since 2023, citing elevated inflation.",
    numbers: [
      ["Target range, Sep 17, 2026 →", "3.75–4.00%"],
      ["Previous range (Dec 2025 – Sep 2026)", "3.50–3.75%"],
      ["Mar 2020 – Mar 2022", "0–0.25%"],
      ["Jul 2023 – Sep 2024", "5.25–5.50%"],
      ["Early 1981 (Volcker)", "≈ 20%"],
    ],
    numbersSource: "Federal Reserve FOMC statements.",
    graph: "inflationVsRates",
  },
  {
    id: "recent-inflation", n: 89, week: W, starred: true, tags: ["PE Q10"],
    term: "Causes of the recent inflation",
    simple: "<b>Supply</b>: COVID disrupted supply chains and the workforce. <b>Demand</b>: monetary and fiscal stimulus boosted spending.",
    more: [
      "Supply side: shipping snarls, chip shortages, workers out sick or retiring, and in 2022 the energy and food shock from Russia's invasion of Ukraine.",
      "Demand side: about $5 trillion of pandemic fiscal relief, near-zero interest rates and Fed asset purchases, and a shift in spending from services to goods that supply couldn't meet.",
    ],
    connections: ["inflation", "qt-growth-rates", "fed-funds"],
    example: "Used-car prices rose about 40% in a year in 2021 because a chip shortage stopped new-car production just as stimulus-funded demand surged: supply and demand at once.",
    numbers: [
      ["CPI peak, Jun 2022 (12-mo.)", "9.1%"],
      ["2022 annual average", "8.0%, highest since 1981"],
      ["Aug 2026", "3.4%"],
    ],
    numbersSource: "BLS CPI.",
    graph: "cpiHistory",
  },
  {
    id: "classical-combined", n: 90, week: W, tags: ["PS3"],
    term: "Classical combined model",
    simple: "The real side sets r from S = I(r); money growth sets π; then i = r + π. Higher G raises r and i but not inflation.",
    more: [
      "Step through it in order: (1) production function → Y. (2) loanable funds → r. (3) quantity theory → π. (4) Fisher → i. (5) money demand with that i → P.",
      "This is the classical dichotomy in action: the money block takes r as given; the real block never looks at M.",
    ],
    connections: ["loanable-funds", "qt-growth-rates", "fisher-equation", "classical-dichotomy"],
    played: [
      "Loanable funds gives r = 5%. Money grows 4%, Y grows 1% → π = 3%. So i = 8%.",
      "Now G rises: S falls, r rises to 7%. π still 3% (money growth unchanged). i rises to 10%.",
    ],
    graph: { key: "loanableFunds", args: { shift: "left" } },
  },
];
